import { createApp } from './app.js';
import { loadEnv } from './config/env.js';
import { connectDatabase } from './database.js';
import { createAuthService } from './domains/auth/auth.service.js';
import { createTokenService } from './domains/auth/token.service.js';
import { mongoUserRepository } from './repositories/user.repository.js';
import { createLogger } from './shared/logger.js';
import { safeErrorMetadata } from './shared/safe-error.js';
import { createCourseService } from './domains/course-management/course.service.js';
import { courseRepository, enrollmentRepository, lessonRepository, withTransaction } from './domains/course-management/course.repository.js';
import { assessmentRepository } from './domains/assessments/assessment.repository.js';
import { createAssessmentService } from './domains/assessments/assessment.service.js';
import { createEnrollmentService } from './domains/enrollments/enrollment.service.js';
import { enrollmentCourseRepository, enrollmentLifecycleRepository } from './domains/enrollments/enrollment.repository.js';
import { classroomRepository, withClassroomTransaction } from './domains/virtual-classroom/virtual-classroom.repository.js';
import { createVirtualClassroomService } from './domains/virtual-classroom/virtual-classroom.service.js';
import { createNotificationService, notificationDispatcher } from './domains/notifications/notification.service.js';
import { calendarAnalyticsRepository } from './domains/calendar-analytics/calendar-analytics.repository.js';
import { createCalendarAnalyticsService } from './domains/calendar-analytics/calendar-analytics.service.js';
import { createInternalAiTokenService } from './domains/ai-integration/internal-ai-token.service.js';
import { createAiClient } from './domains/ai-integration/ai-client.js';
import { aiIntegrationRepository } from './domains/ai-integration/ai-integration.repository.js';
import { createAiIntegrationService } from './domains/ai-integration/ai-integration.service.js';
import { seedLocalUsers } from './dev/seed-local.js';

const config = loadEnv();
const logger = createLogger(config.LOG_LEVEL);
const tokens = createTokenService(config);
const authService = createAuthService({ users: mongoUserRepository, tokens, logger });
const notificationService = createNotificationService({ logger });
const assessmentService = createAssessmentService({ repo: assessmentRepository, logger, transaction: withTransaction, notificationDispatcher });
const courseService = createCourseService({ courses: courseRepository, lessons: lessonRepository, enrollments: enrollmentRepository, transaction: withTransaction, finalizeEligibilityLoss: assessmentService.finalizeEligibilityLoss });
const enrollmentService = createEnrollmentService({ enrollments: enrollmentLifecycleRepository, courses: enrollmentCourseRepository, transaction: withTransaction, finalizeEligibilityLoss: assessmentService.finalizeEligibilityLoss });
const virtualClassroomService = createVirtualClassroomService({ repo: classroomRepository, transaction: withClassroomTransaction, config, logger });
const calendarAnalyticsService = createCalendarAnalyticsService({ repo: calendarAnalyticsRepository, logger });
const internalAiTokens = createInternalAiTokenService(config);
const aiClient = createAiClient({ config, tokenService: internalAiTokens, logger });
const aiIntegrationService = createAiIntegrationService({ repo: aiIntegrationRepository, client: aiClient, assessmentService, config });

await connectDatabase(config.MONGODB_URI, logger);
if (config.seedLocalUsers) await seedLocalUsers(logger);
const server = createApp({ config, logger, authService, tokens, courseService, assessmentService, enrollmentService, virtualClassroomService, calendarAnalyticsService, notificationService, aiIntegrationService }).listen(config.PORT, () => logger.info({ port: config.PORT, serveWeb: config.serveWeb }, 'Core API listening'));
const expirySweep = setInterval(() => assessmentService.processExpired().catch((error) => logger.error({ ...safeErrorMetadata(error), event: 'assessment_expiry_sweep_failed' }, 'Assessment expiry sweep failed')), 30000).unref();
for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, () => { clearInterval(expirySweep); });
for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, () => server.close(() => process.exit(0)));
